version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - 3002:3002
    depends_on: 
      - postgres
    environment:
      DB_HOST: postgres
      DB_USER: admin
      DB_PASSWORD: password123
      DB_NAME: taskapp
  postgres:
    image: postgres:18-alpine
    ports: 
      - 5432:5432   #ASK
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: taskapp
    volumes: 
      - db_data:/var/lib/postgresql/data/
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
  frontend:
    build: ./frontend
    ports: 
      - 3001:3001

volumes:
  db_data: